Capture page apply responsivity
lisbom-dev/records-gatsby pull request #1
Opened 2022-09-08 04:50 UTC by guilherme-gjv

2022-09-08 05:06 UTC, guilherme-gjv commented
## 2XL @media (min-width: 1536px)

![image](https://user-images.githubusercontent.com/83377948/189037103-810c72e2-1d5c-4bff-8ac6-5da408b3de10.png)

## XL @media (min-width: 1280px)

![image](https://user-images.githubusercontent.com/83377948/189038444-d39a5799-b46d-419a-a418-b7df67f94197.png)

## LG @media (min-width: 1024px)

![image](https://user-images.githubusercontent.com/83377948/189037885-a08dcf01-8512-4d2c-a6a0-4079fbb4129e.png)

## MD @media (min-width: 768px)

![image](https://user-images.githubusercontent.com/83377948/189038122-5e08835b-abda-4d13-9921-4fcac53b1e3a.png)

## SM @media (min-width: 640px)

![image](https://user-images.githubusercontent.com/83377948/189038636-82af4053-e6d3-4a01-aa95-0242689e6ef2.png)

## < SM

![image](https://user-images.githubusercontent.com/83377948/189038748-107e35f7-eae8-4cd6-9ea4-4f1b84db8ec5.png)

2022-09-09 02:50 UTC, LOFyz requested changes
Solve my comments and request review again. This pull request if approved, can just be merged after the images being added.

2022-09-09 02:50 UTC, LOFyz commented on src/pages/captura.tsx
> +              className="uppercase absolute inset-x-0 -bottom-5 xl:text-xl 2xl:text-[1.875rem]"
Fix this `-` on the left of the class `bottom-5`

2022-09-09 02:50 UTC, LOFyz commented on src/pages/captura.tsx
> +              style={twButton(70)}
Remove this style prop. Make this only with class. Make it with [@apply](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply), create a plugin or make normally in className

2022-09-09 02:50 UTC, LOFyz commented on src/pages/captura.tsx
> +              style={twButton(70)}
Same as the other comment

2022-09-09 02:50 UTC, LOFyz commented on src/pages/captura.tsx
> +          <img src="" alt="fofo" />
Fix this alt when adding the image

2022-09-09 17:17 UTC, guilherme-gjv commented on src/pages/captura.tsx
> +              className="uppercase absolute inset-x-0 -bottom-5 xl:text-xl 2xl:text-[1.875rem]"
The ``-`` is for negative bottom position

2022-09-12 07:45 UTC, merged